apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: cashback-bot
type: Opaque
stringData:
  BOT_TOKEN: ""  # Заполните токен бота
  DEEPSEEK_API_KEY: ""  # Заполните API ключ
  YANDEX_GPT_API_KEY: ""  # Опционально
  YANDEX_GPT_FOLDER_ID: ""  # Опционально
  SENTRY_DSN: ""  # Опционально

