apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cashback-bot

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - bot-secret.yaml
  - bot-configmap.yaml
  - bot-deployment.yaml
  - bot-service.yaml
  # - job-migrations.yaml  # Раскомментируйте для первого запуска

