apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cashback-bot
type: Opaque
stringData:
  POSTGRES_DB: cashback_bot
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me-please  # Измените на безопасный пароль!

